add debug mode for non-x64
taosdata/taos-tools pull request #131
Opened 2022-02-11 02:38 UTC by zhaoyanggh

2022-02-12 08:58 UTC, sangshuduo commented on deps/CMakeLists.txt
> +IF (TD_ARM_32)
I suggest modifying compile option in the release section only and using add_compile_options() to avoid affecting globally.

2022-02-12 09:00 UTC, sangshuduo requested changes
Please hold this PR. We should find a solution with minimal effection.

2022-02-14 04:53 UTC, sangshuduo approved these changes
LGTM

2022-02-14 05:01 UTC, afwerar approved these changes
LGTM

2022-02-14 05:18 UTC, merged