[TD-11626]<feature>taosdemo support pressure test compare with perfMonitor
taosdata/taos-tools pull request #20
Opened 2021-12-02 07:46 UTC by zhaoyanggh

only in taosc progressive mode

2021-12-02 07:59 UTC, afwerar approved these changes
LGTM

2021-12-02 09:16 UTC, sangshuduo commented on src/demoInsert.c
> +      stbInfo->buffer = calloc(1, stbInfo->columnCount*2 + 2 );
indent

2021-12-02 09:19 UTC, sangshuduo requested changes

2021-12-02 09:19 UTC, sangshuduo commented on src/demoInsert.c
> +              printf("thread[%d] has currently inserted rows: %" PRId64
indent

2021-12-02 09:19 UTC, sangshuduo commented on src/demoInsert.c
> +              printf("[%d]:%d%%\n", pThreadInfo->threadID, currentPercent);
indent

2021-12-02 09:19 UTC, sangshuduo commented on src/demoInsert.c
> +              errorPrint("affected rows: %d\n", affectedRows);
indent

2021-12-02 09:19 UTC, sangshuduo commented on src/demoInsert.c
> +                generated = prepareStmtWithoutStb(pThreadInfo, tableName, g_args.reqPerReq, insertRows, i, start_time);
indent

2021-12-02 09:19 UTC, sangshuduo commented on src/demoInsert.c
> +                generated = generateProgressiveDataWithoutStb(tableName,
indent

2021-12-02 09:19 UTC, sangshuduo commented on src/demoInsert.c
> +          if (g_args.pressure_mode) {
indent

2021-12-03 03:04 UTC, sangshuduo commented on inc/demo.h
> +    char                cfgDir[MAX_FILE_NAME_LEN];
align

2021-12-03 03:04 UTC, sangshuduo commented on inc/demo.h
> +    char                cfgDir[MAX_FILE_NAME_LEN];
align

2021-12-03 03:04 UTC, sangshuduo commented on inc/demo.h
> +    char                user[MAX_USERNAME_SIZE];
align

2021-12-03 03:08 UTC, sangshuduo approved these changes
still few lines align mistake. not big deal but please correct them.

2021-12-03 03:29 UTC, sangshuduo approved these changes
my mistake. LGTM

2021-12-03 03:30 UTC, merged