[TD-11715]<fix>taosdemo sml unsupport sample
taosdata/taos-tools pull request #22
Opened 2021-12-02 10:12 UTC by zhaoyanggh

2021-12-02 10:22 UTC, sangshuduo commented on src/demoInsert.c
> +      } else {
indent

2021-12-02 10:28 UTC, sangshuduo requested changes

2021-12-02 10:28 UTC, sangshuduo commented on src/demoInsert.c
> +      if (prepareSampleData()) {
indent

2021-12-03 03:34 UTC, sangshuduo approved these changes
LGTM

2021-12-03 03:35 UTC, afwerar approved these changes
LGTM

2021-12-03 03:37 UTC, merged