[TD-12458]<fix>taosBenchmark restfult full response
taosdata/taos-tools pull request #65
Opened 2021-12-27 10:30 UTC by zhaoyanggh

2021-12-27 10:47 UTC, afwerar approved these changes
LGTM

2021-12-27 15:42 UTC, sangshuduo commented on inc/demo.h
> +#define DEFAULT_REQ_PER_REQ 10000
I worry this change would significantly decrease the insertion performance.

2021-12-27 15:43 UTC, sangshuduo requested changes
see my comments

2021-12-28 05:35 UTC, merged

2021-12-30 05:52 UTC, sangshuduo reviewed
LGTM